---
include:
  - board: nice_nano
    shield: charybdis_left
    keymap: qwerty
    format: bt
    artifact-name: charybdis_qwerty_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: charybdis_right
    keymap: qwerty
    format: bt
    artifact-name: charybdis_qwerty_right
  - board: nice_nano
    shield: settings_reset
    format: reset
    artifact-name: firmware_reset_nano
